### ISSUE TITLE
Missing united_states_capitol sequences in the test data

### ISSUE THREAD

**Issue by Prinsphield** [ubc-vision/image-matching-benchmark-baselines#10]
Hello, I have downloaded the test data [here](https://www.cs.ubc.ca/~kmyi/imw2020/data.html). However, I found the sequence named "united_states_capitol" is missing in the data.

**Comment by etrulls** [comment]
That scene was removed long ago, as it was the rare example that is too difficult to pose with standard SfM frameworks (rounded cupola, repeated structures, very similar front/back) even with a lot of data, and we found that a few images were not posed correctly. It's not listed in the paper or the website, and has not been used in the last two challenges, so I don't know where you saw the reference -- please let us know so we can delete it.

**Comment by ducha-aiki** [comment]
We have removed it due to the problems in ground truth, see the paper.
https://arxiv.org/pdf/2003.01587

**Comment by etrulls** [comment]
Nevermind, I see. This is the baselines repo, not the benchmark repo (didn't notice). It's possible that there are a few references left here, as we don't really use this repository anymore. If you want to use this, feel free to just delete the scene if you see it listed in a json file.

**Comment by ducha-aiki** [comment]
@Prinsphield if you need some example code to run your own method, you might be better off using this tutorials and associated repository:

tutorial: https://ducha-aiki.github.io/wide-baseline-stereo-blog/2021/05/12/submitting-to-IMC2021-step-by-step.html
custom matcher:  https://ducha-aiki.github.io/wide-baseline-stereo-blog/2021/05/27/submitting-to-IMC2021-with-custom-matcher.html

repo: https://github.com/ducha-aiki/imc2021-sample-kornia-submission

Just keep in mind that GoogleUrban dataset is no longer available and you need to skip it.

**Comment by Prinsphield** [comment]
Thanks for pointing to the tutorial. May I know is it necessary to run the following command for our new method? 
```
python -utt run.py --run_mode=interactive --json_method=../imc2021-sample-kornia-submission/base_config.json --subset=val  --path_data ../imc-2021-data/ --path_results ../benchmark-results --is_challenge false
```
Following the tutorial above, I found that `--kp_name cv2dog --desc_name affnethardnet8` are not implemented in `run.py`, which would cause error `raise RuntimeError('Unknown keypoint/descriptor combination')` in the `compute_feature.py` file. What should I do if I want to submit my own method? Since the keypoint the descriptor methods are not implemented in the `run.py` file.

**Comment by ducha-aiki** [comment]
I am afraid, that you have not looked carefully into tutorials. There is cv2dog or affnethardnet features in the baseline repository. Instead first tutorial shows how to extract them (and provides all necessary code). Then you import the extracted features under this names 'cv2dog' and 'affnethardnet'  with import_features.py

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4803565/126610979-000f18ef-905b-45ac-92b8-cb50e59715c4.png">

Then you can do run.py

**Comment by Prinsphield** [comment]
I was trying to run the R2D2 method only on the phototourism dataset.

Here is the config.json file. I have also run `import_features.py` already.
```
[
  {
    "metadata": {
      "publish_anonymously": true,
      "authors": "xxx",
      "contact_email": "xxx@gmail.com",
      "method_name": "R2D2-wasf-n16-8k",
      "method_description": "R2D2-wasf-n16-8k",
      "link_to_website": "",
      "link_to_pdf": ""
    },
    "config_common": {
      "json_label": "r2d2-wasf-n16-8k",
      "keypoint": "r2d2",
      "descriptor": "r2d2",
      "num_keypoints": 8000
    },
    "config_phototourism_stereo": {
      "use_custom_matches": true,
      "custom_matches_name": "r2d",
      "geom": {
        "method": "cv2-8pt"
      }
    },
    "config_phototourism_multiview": {
      "use_custom_matches": true,
      "custom_matches_name": "r2d2",
      "colmap": {}
    }
  }
]
```

Here is the error! Could you please take a look at it? The error `raise RuntimeError('Unknown keypoint/descriptor combination')` was due to that `--kp_name r2d2` and  `--desc_name r2d2` are not implemented in `run.py`.

```
Validating method 1/1: "r2d2-wasf-n16-8k"
['phototourism', 'pragueparks', 'googleurban']
Running: phototourism, stereo track
Running: phototourism, multiview track
Validating key "config_phototourism_stereo"
Validating key "config_phototourism_multiview"
Key "config_pragueparks_stereo" is not present. Skipping check.
Key "config_pragueparks_multiview" is not present. Skipping check.
Key "config_googleurban_stereo" is not present. Skipping check.
Key "config_googleurban_multiview" is not present. Skipping check.
Working on r2d2-wasf-n16-8k: phototourism/reichstag
 -- Computing feature
WARNING: ./jobs/ce4ae7e4e9641de97e8be27cdffe3c3658dcc8deb6bda2f98e492b85c3fcc3f6 already exists!
Extracting Keypoints and Descriptors:
  0%|                                                                                       | 0/74 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "compute_feature.py", line 172, in <module>
    main(cfg)
  File "compute_feature.py", line 124, in main
    result.append(compute_per_img_file(img_path, cfg))
  File "compute_feature.py", line 85, in compute_per_img_file
    raise RuntimeError('Unknown keypoint/descriptor combination')
RuntimeError: Unknown keypoint/descriptor combination
Traceback (most recent call last):
  File "run.py", line 280, in <module>
    main(cfg)
  File "run.py", line 215, in main
    job_dict)
  File "run.py", line 47, in create_eval_jobs
    job = create_and_queue_jobs(cmd_list, cfg, dep_str)
  File "/home/taihong/work/keypoint-eval/image-matching-benchmark/utils/queue_helper.py", line 310, in create_and_queue_jobs
    cpu=cpu)
  File "/home/taihong/work/keypoint-eval/image-matching-benchmark/utils/queue_helper.py", line 161, in queue_job
    raise RuntimeError('Subprocess error!')
RuntimeError: Subprocess error!
```

**Comment by ducha-aiki** [comment]
I am sorry, but there is no R2D2 either in the main benchmark repo. That is why, it is completely reasonable, that you are getting this error. 


The scripts for extracting R2D2 are in this (where we are discussing) repo, but it does not automatically connect to the main. You should run the extraction yourself, as it is stated in readme https://github.com/ubc-vision/image-matching-benchmark-baselines#r2d2

**Comment by Prinsphield** [comment]
I have already done the feature extraction for R2D2. So my question is: what do `import_features.py` and `run.py` do and do I need to run `run.py` in order to make a submission?

**Comment by etrulls** [comment]
Dmytro: He says he ran `import_features.py` though, so I guess he extracted and imported the features somehow? As Dmytro says, you need to generate them with that repo (or by any other means) then import them.

The benchmark is trying to compute the features (see "-- Computing feature") because it doesn't find them in the output cache folder, and since the method is not built-in (like SIFT or ORB), it crashes, so they are not imported correctly. Maybe the path is incorrect, of you used the wrong name or number of features? If you cat the ./jobs file it should have all the paths (if I remember correctly), please check that the files are there.

In addition, please note that you named the custom matches "r2d" in the json, instead of "r2d2" (it should work if you also import the matches as "r2d" when using the import script, but I guess this was a typo).

**Comment by etrulls** [comment]
> Do I need to run run.py in order to make a submission?

Please note that to make a submission you don't need to import any features or use the benchmark at all. You just send us the features and the json file, as outlined in the website. If you want to run the benchmark it should be for validation (finding the right hyperparameters) as the test set is hidden anyway.

**Comment by Prinsphield** [comment]
> > Do I need to run run.py in order to make a submission?
> 
> Please note that to make a submission you don't need to import any features or use the benchmark at all. You just send us the features and the json file, as outlined on the website. If you want to run the benchmark it should be for validation (finding the right hyperparameters) as the test set is hidden anyway.

So how can I run the benchmark for validation use if the keypoint and descriptor methods are not supported in the `run.py`? I have already submitted the extracted feature and descriptors with the generated json file to the website. May I know how long can I see the result? How can I see the results privately as I have set `publish_anonymously: true` in the json file?  BTW, for the R2D2 outputs, I only have `descriptors.h5`, `keypoints.h5`, `scales.h5` and `scores.h5` in each sqeuence. However, I have also noticed that exists `matches.h5` in the tutorial. So what is it and is it necessary though I have run `submission_validator.py` and it says no problem before making a submission?

**Comment by ducha-aiki** [comment]
Import_features moves the features into the directory, where benchmark looks for them, under the detector-descriptor combination which you specified in the import_features run and which should coincide with names in your json.
Run.py does run the evaluation on the val (available for you) or test set (not available for you)

**Comment by ducha-aiki** [comment]
You cannot run on val most likely because of the name mismatch, in your json and the ones you used when run import_features.py.
Matches are necessary only if you specify custom matcher in your json. Check the 1st tutorial, not the second.

**Comment by ducha-aiki** [comment]
I also apologize, but I believe, that the most efficient way to run on the validation, would be to perform all the steps in the tutorial
https://ducha-aiki.github.io/wide-baseline-stereo-blog/2021/05/12/submitting-to-IMC2021-step-by-step.html
without any changes until you see the results of evaluation, Then adapt it to your features.

**Comment by etrulls** [comment]
I think this is just getting confusing. Let me try to clear it up. If you want to run the benchmark for validation, you have to:

1. Extract features for the validation scenes (and matches if you want)
2. Import them
3. Run the benchmark

If the feature is "built-in" (such as SIFT), you can ignore steps 1 and 2, but the vast majority are not. Built-in features are just cv2 wrappers, we can't embed every single method into the benchmark. You import those.

> I have already submitted the extracted feature and descriptors with the generated json file to the website. May I know how long can I see the result?

I saw a submission a few hours ago. If it's correct, it will be processed and uploaded within hours/a few days. You can check the status [here](https://docs.google.com/spreadsheets/d/1YnVHcLqBpXtN-r6o0Of7hjs6htcwxu5w7mLsrxnIaxk/edit#gid=0) (this spreadsheet is filled by hand so there's nothing there yet, as our colleagues on the west coast are not up yet).

> How can I see the results privately as I have set publish_anonymously: true in the json file?

All submissions are listed in the leaderboards, we just hide details and contact data if you enable that flag.

> BTW, for the R2D2 outputs, I only have descriptors.h5, keypoints.h5, scales.h5 and scores.h5 in each sqeuence. However, I have also noticed that exists matches.h5 in the tutorial. So what is it and is it necessary though I have run submission_validator.py and it says no problem before making a submission?

You can submit custom matches, if you want. The tutorial shows you a way to do that. If you don't have any matcher you'd like to use, you can use the built-in matchers.

You cannot import matches you don't have, so in your example you should use the built-in matchers. See an example [here](https://www.cs.ubc.ca/research/image-matching-challenge/2021/submit/).
