### ISSUE TITLE
Missing L2Net model

### ISSUE THREAD

**Issue by mesaperry** [ubc-vision/image-matching-benchmark-baselines#5]
misc/l2net/l2net_model.py doesn't exist, preventing L2Net from running

**Comment by etrulls** [comment]
Mmm, I think something got lost in one of the refactorings.
@DagnyT @ducha-aiki Can you have a look?

**Comment by ducha-aiki** [comment]
Fixed now https://github.com/ubc-vision/image-matching-benchmark-baselines/commit/b3fb3a7ea43fe60da490cd88bd5191142373b494
