### ISSUE TITLE
The pyramid scale is 2 in the function of extract_patches

### ISSUE THREAD

**Issue by kkzh2313** [ubc-vision/image-matching-benchmark-baselines#6]
In the Opencv ORB algorithm implementation, the default pyramid scale is 1.2 and the number of layers is usually 8. 
However,the pyramid scale is 2 in  the extract_patches/core.py . The code is expressed at line 98( pyr_idx = max(0, int(math.log(s,2))); d_factor = float(math.pow(1.2,pyr_idx))).
Is it correct to extract patches directly using the function of extract_patches  for ORB key points?

**Comment by kkzh2313** [comment]
Add: The url of the extract-patches library is at https://pypi.org/project/extract-patches/

**Comment by ducha-aiki** [comment]
Hi,
first, we don't use extract_patches for ORB. Even, if we would, unlike in ORB, which just crops patch_size from pyramid -- that is why one needs 1.2 fine pyramid, we use pyramid only as proper blurring, and then crop exactly area needs to be described and then resize patch_size.
So, yes, it would be correct. 
However, it would kill fast ORB speed.

**Comment by kkzh2313** [comment]
Hello, I'm sorry I have another question.

Is there any specific reference to the transformation matrix? I don't understand its specific mathematical principles very well.

The specific code of the matrix which is in the extract_patchees/core.py is as follows : 
M = np.matrix([
            [+s_pyr * cos, -s_pyr * sin, (-s_pyr * cos + s_pyr * sin) * PS / 2.0 + x/d_factor],
            [+s_pyr * sin, +s_pyr * cos, (-s_pyr * sin - s_pyr * cos) * PS / 2.0 + y/d_factor]])

**Comment by ducha-aiki** [comment]
See here, 
https://cw.fel.cvut.cz/b192/courses/mpv/labs/2_correspondence_problem/start

Section 2, Computing local invariant description.

The code is required to get the properly scaled and rotated patch, so that roughly the same image content to be described, regardless of the camera position.
![image](https://user-images.githubusercontent.com/4803565/93756578-9b5fbc00-fc05-11ea-9b09-b890ba41d4db.png)
