### ISSUE TITLE
About system/hardnet.yml

### ISSUE THREAD

**Issue by felipecadar** [ubc-vision/image-matching-benchmark-baselines#8]
The yml specifies :  python=3.5.6=hc3d631a_0 ([line](https://github.com/ubc-vision/image-matching-benchmark-baselines/blob/27118d984cc9bd675569bd45b716543c8a6c43d7/system/hardnet.yml#L81))

and extract_patches expect python >= 3.6.2 ([line](https://github.com/ducha-aiki/extract_patches/blob/58970076bdacc2c1a3cb5617a0408edca57adcd2/setup.py#L4))

but when i change python to 3.7 i got the error:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cffi==1.11.5=py35he75722e_1 -> python[version='>=3.5,<3.6.0a0'] -> python_abi=[build=*_cp35m] -> pypy[version='<0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

How to proceed ?

**Comment by etrulls** [comment]
Can you try removing the version number from cffi? Or just removing the line altogether (it'll be installed if necessary).

**Comment by felipecadar** [comment]
It keeps happening with every other package 

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - prompt_toolkit==1.0.15=py35hc09de7a_0 -> python[version='>=3.5,<3.6.0a0'] -> python_abi=[build=*_cp35m] -> pypy[version='<0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
--------------------------------------------------------------------
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - scipy==1.1.0=py35hd20e5f9_0 -> python[version='>=3.5,<3.6.0a0'] -> python_abi=[build=*_cp35m] -> pypy[version='<0a0']
Use "conda info <package>" to see the dependencies for each package.
--------------------------------------------------------------------
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - ipython_genutils==0.2.0=py35hc9e07d0_0 -> python[version='>=3.5,<3.6.0a0'] -> python_abi=[build=*_cp35m] -> pypy[version='<0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

Do i have to update every package ?

**Comment by felipecadar** [comment]
Im going to clone extract_patches repo and change the setup.py to accept older versions and see if it runs...

**Comment by kmyi** [comment]
You are using Python 3.7. Our environment is set using Python 3.5. Since conda has moved onto newer versions, you should then simply remove all version information and try with that. It should not have any drastic breaking changes though.

Kwang

**Comment by kmyi** [comment]
Another thing you can try is to simply remove all the "=py35hc9e07d0_0" things. I think that might work.

**Comment by etrulls** [comment]
I think you can actually remove the version names (everything after the first equal sign). There was an issue with pyransac and python 3.7 though, if I remember correctly. I might be misremembering, @ducha-aiki may know more.

**Comment by felipecadar** [comment]
I can use python 3.5, but i cant install the package extract_patches with this version. I even used the old conda version suggested in the repo.

> You are using Python 3.7. Our environment is set using Python 3.5. Since conda has moved onto newer versions, you should then simply remove all version information and try with that. It should not have any drastic breaking changes though. Kwang

**Comment by felipecadar** [comment]
I´m afraid pytorch will come with the wrong version, I just wanna know how to install extract_patches in python 3.5

> I think you can actually remove the version names (everything after the first equal sign). There was an issue with pyransac and python 3.7 though, if I remember correctly. I might be misremembering, @ducha-aiki may know more.

**Comment by etrulls** [comment]
Ah yeah, I misremembered, it's extract_patches that needs 3.6+, because of the "typing" package dependency. I think you can use 3.6 (or 3.7) and install the dependencies ignoring version numbers, one at a time if necessary. I'll try to update the yml file at some point (after the ICCV deadline). Sorry about the bother, but it should just work that way.

**Comment by felipecadar** [comment]
It worked! Thanks

btw, this is the yml i used https://gist.github.com/felipecadar/95ee705a7a3bae2cbc79812002b68541

**Comment by etrulls** [comment]
Glad to hear it! I'll close the issue and update the yml file in a few days. Let us know if you have other problems with it.
