### ISSUE TITLE
lfnet url invalid

### ISSUE THREAD

**Issue by JimPlayboy** [ubc-vision/image-matching-benchmark-baselines#9]
it seems that the url to download a pretrained model of lfnet is no longer valid. how can i find a pretrained model of lfnet

**Comment by kmyi** [comment]
It should now be fixed. There was a typo when migrating links.

wget https://cs.ubc.ca/research/kmyi_data/files/2018/lf-net/lfnet-norotaug.tar.gz -O third_party/lfnet/release/lfnet-norotaug.tar.gz

**Comment by JimPlayboy** [comment]
thank you! it worked! :+1:

**Comment by JimPlayboy** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kwang Moo ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 凌晨1:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ubc-vision/image-matching-benchmark-baselines] lfnet url invalid (#9)





 
It should now be fixed. There was a typo when migrating links.
 
wget https://cs.ubc.ca/research/kmyi_data/files/2018/lf-net/lfnet-norotaug.tar.gz -O third_party/lfnet/release/lfnet-norotaug.tar.gz
